version: '3.1'

services:
  database:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: mydb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build: ./webpage
    ports:
      - "8080:80"
    depends_on:
      - database
    volumes:
      - ./webpage:/var/www/html
